all: one two three

CC = g++
WORK1 = string
WORK2 = dynamic_array
WORK3 = function_overloading

one:
	$(CC) $(WORK1).cc -o $(WORK1)

two:
	$(CC) $(WORK2).cc -o $(WORK2)

three:
	$(CC) $(WORK3).cc -o $(WORK3)
clean:
	rm -rf $(WORK1) $(WORK2) $(WORK3)
