version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: install dependencies
          command: apt-get update && apt-get install -yy build-essential g++ cmake
      - run:
          name: make all projects
          command: ./make_all_projects.sh

