all: first second third

CC = g++
WORK1 = array_2dim
WORK2 = touch_points
WORK3 = cal_complex

first:
	$(CC) $(WORK1).cc -o $(WORK1)
second:
	$(CC) $(WORK2).cc -o $(WORK2)
third:
	$(CC) $(WORK3).cc -o $(WORK3)
clean:
	rm -rf $(WORK1) $(WORK2) $(WORK3)

