all: first second third

CC = g++
WORK1 = array_2dim
WORK2 = touch_points
WORK3 = cal_complex

first:
	$(CC) -std=c++11 $(WORK1).cc -o $(WORK1)
second:
	$(CC) -std=c++11 $(WORK2).cc -o $(WORK2)
third:
	$(CC) -std=c++11 $(WORK3).cc -o $(WORK3)
clean:
	rm -rf $(WORK1) $(WORK2) $(WORK3)

